-- Migration 067: Add public endpoint rate-limit table and scope link_accesses idempotency by link
-- Date: 2026-02-25

BEGIN;

-- ============================================================================
-- LINK_ACCESSES IDEMPOTENCY: UNIQUE PER LINK
-- ============================================================================

ALTER TABLE public.link_accesses
  DROP CONSTRAINT IF EXISTS link_accesses_event_id_unique;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'link_accesses_link_id_event_id_unique'
      AND conrelid = 'public.link_accesses'::regclass
  ) THEN
    ALTER TABLE public.link_accesses
      ADD CONSTRAINT link_accesses_link_id_event_id_unique UNIQUE (link_id, event_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_link_accesses_link_event_created
  ON public.link_accesses(link_id, event_id, created_at DESC);

COMMENT ON CONSTRAINT link_accesses_link_id_event_id_unique ON public.link_accesses IS
  'Idempotência técnica por evento no contexto do link';

-- ============================================================================
-- EDGE RATE LIMITS TABLE (PUBLIC ENDPOINT PROTECTION)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.edge_rate_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint_key TEXT NOT NULL,
  ip_address TEXT NOT NULL,
  request_path TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_edge_rate_limits_endpoint_ip_created
  ON public.edge_rate_limits(endpoint_key, ip_address, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_edge_rate_limits_created_at
  ON public.edge_rate_limits(created_at DESC);

ALTER TABLE public.edge_rate_limits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS edge_rate_limits_no_access ON public.edge_rate_limits;
CREATE POLICY edge_rate_limits_no_access
  ON public.edge_rate_limits
  FOR ALL
  USING (FALSE)
  WITH CHECK (FALSE);

COMMENT ON TABLE public.edge_rate_limits IS
  'Registro técnico para proteção de endpoints públicos via rate limiting';

COMMENT ON COLUMN public.edge_rate_limits.endpoint_key IS
  'Chave lógica do endpoint público (ex.: register-access, by-slug)';

COMMIT;
